 export const optionsMark = [
    { value: 'AC', label: 'AC' },
    { value: 'Alfa Romeo', label: 'Alfa Romeo' },
    { value: 'Aro', label: 'Aro' },
    { value: 'Asia Motors', label: 'Asia Motors' },
    { value: 'Audi', label: 'Audi' },
    { value: 'Austin', label: 'Austin' },
    { value: 'BAW', label: 'BAW' },
    { value: 'Bentley', label: 'Bentley' },
    { value: 'BMW', label: 'BMW' },
    { value: 'Buick', label: 'Buick' },
    { value: 'Cadillac', label: 'Cadillac' },
    { value: 'Chery', label: 'Chery' },
    { value: 'Chevrolet', label: 'Chevrolet' },
    { value: 'Chrysler', label: 'Chrysler' },
    { value: 'Citroen', label: 'Citroen' },
    { value: 'Cupra', label: 'Cupra' },
    { value: 'Dacia', label: 'Dacia' },
    { value: 'Daewoo', label: 'Daewoo' },
    { value: 'Dodge', label: 'Dodge' },
    { value: 'DR', label: 'DR' },
    { value: 'DS', label: 'DS' },
    { value: 'Ferrari', label: 'Ferrari' },
    { value: 'Fiat', label: 'Fiat' },
    { value: 'Ford', label: 'Ford' },
    { value: 'GAZ', label: 'GAZ' },
    { value: 'Honda', label: 'Honda' },
    { value: 'Hummer', label: 'Hummer' },
    { value: 'Hyundai', label: 'Hyundai' },
    { value: 'Infiniti', label: 'Infiniti' },
    { value: 'Isuzu', label: 'Isuzu' },
    { value: 'Jaguar', label: 'Jaguar' },
    { value: 'Jeep', label: 'Jeep' },
    { value: 'Kia', label: 'Kia' },
    { value: 'Lada', label: 'Lada' },
    { value: 'Lamborghini', label: 'Lamborghini' },
    { value: 'Lancia', label: 'Lancia' },
    { value: 'Land Rover', label: 'Land Rover' },
    { value: 'Lexus', label: 'Lexus' },
    { value: 'Lincoln', label: 'Lincoln' },
    { value: 'Maserati', label: 'Maserati' },
    { value: 'Mazda', label: 'Mazda' },
    { value: 'Mercedes Benz', label: 'Mercedes Benz' },
    { value: 'Mercury', label: 'Mercury' },
    { value: 'MINI', label: 'MINI' },
    { value: 'Mitsubishi', label: 'Mitsubishi' },
    { value: 'Nissan', label: 'Nissan' },
    { value: 'Opel', label: 'Opel' },
    { value: 'Peugeot', label: 'Peugeot' },
    { value: 'Piaggio', label: 'Piaggio' },
    { value: 'Polski Fiat', label: 'Polski Fiat' },
    { value: 'Pontiac', label: 'Pontiac' },
    { value: 'Porsche', label: 'Porsche' },
    { value: 'Renault', label: 'Renault' },
    { value: 'Rolls Royce', label: 'Rolls Royce' },
    { value: 'Rover', label: 'Rover' },
    { value: 'Saab', label: 'Saab' },
    { value: 'Seat', label: 'Seat' },
    { value: 'Smart', label: 'Smart' },
    { value: 'Subaru', label: 'Subaru' },
    { value: 'Suzuki', label: 'Suzuki' },
    { value: 'Talbot', label: 'Talbot' },
    { value: 'Tesla', label: 'Tesla' },
    { value: 'Toyota', label: 'Toyota' },
    { value: 'UAZ', label: 'UAZ' },
    { value: 'Vauxhall', label: 'Vauxhall' },
    { value: 'Volkswagen', label: 'Volkswagen' },
    { value: 'Volvo', label: 'Volvo' },
    { value: 'Zastava', label: 'Zastava' },
    { value: 'Škoda', label: 'Škoda' },
    { value: 'Ostalo', label: 'Ostalo' }
];

export const optionsType = [
    { value: 'Karavan', label: 'Karavan' },
    { value: 'Limuzina', label: 'Limuzina' },
    { value: 'Hečbek', label: 'Hečbek' },
    { value: 'Kupe', label: 'Kupe' },
    { value: 'Kabriolet', label: 'Kabriolet' },
    { value: 'Kombi', label: 'Kombi' },
    { value: 'Džip', label: 'Džip' },
    { value: 'SUV', label: 'SUV' },
    { value: 'Pikap', label: 'Pikap' }
];

export const optionsGear = [
    { value: 'Manuelni', label: 'Manuelni' },
    { value: 'Automatski', label: 'Automatski' }
];

export const optionsState = [
    { value: 'Nije ostecen', label: 'Nije ostecen' },
    { value: 'Ostecen-vozno stanje', label: 'Ostecen-vozno stanje' },
    { value: 'Ostecen-nije u voznom stanju', label: 'Ostecen-nije u voznom stanju'}
];

export const optionsDrive = [
    { value: 'Prednji', label: 'Prednji' },
    { value: 'Zadnji', label: 'Zadnji' },
    { value: 'Pogon na sva cetiri tocka', label: 'Pogon na sva cetiri tocka'}
];